### ISSUE TITLE
Support for youtube login to download private videos

### ISSUE THREAD

**Issue by ghost** [MayNiklas/docker-youtube-dl-webfrontend#1]
Support for youtube login to download private videos Needed. Thanks.

**Comment by MayNiklas** [comment]
Hey.
Implementing downloading private videos won't be possible.

1. We would need some kind of login for that
2. There isn't a safe way to implement this in the current form of the project
3. Many people (myself included) use 2FA on their accounts -> it would get even more confusing for those who can't use the feature 
4. The project should stay relatively simple

Keep in mind:
I just wrote a simple web front end for youtube-dl... Why don't you simply use the command line application for downloading private videos? It already supports that!

**Comment by ghost** [comment]
Thanks for reply. i understand. better to use command line.
